items = [
    ["sword", 10, "weapon", "A sharp blade for close combat."],
    ["bow", 8, "weapon", "A ranged weapon for attacking from a distance."],
    ["potion", 0, "consumable", "A drink that restores health."],
    ["armor", 0, "armor", "Protective gear that reduces damage taken."],
    ["gold", 0, "currency", "A valuable metal used for trading."],
    ["dagger", 6, "weapon", "A small blade for quick attacks."],
    ["staff", 7, "weapon", "A long stick used for casting spells."],
    ["wand", 5, "weapon", "A short stick used for casting spells."],
    ["crossbow", 9, "weapon", "A ranged weapon that fires bolts."],
    ["axe", 11, "weapon", "A heavy blade for chopping."],
    ["mace", 12, "weapon", "A heavy club with a spiked head."],
    ["spear", 8, "weapon", "A long pole with a sharp tip."],
    ["halberd", 10, "weapon", "A pole weapon with an axe and spearhead."],
    ["shield", 0, "armor", "A protective barrier that blocks attacks."],
    ["helmet", 0, "armor", "A protective headgear that reduces damage taken."],
    ["boots", 0, "armor", "Protective footwear that reduces damage taken."],
    ["gloves", 0, "armor", "Protective hand-wear that reduces damage taken."],
    ["ring", 0, "accessory", "A piece of jewelry that grants magical powers."],
    ["amulet", 0, "accessory", "A necklace that grants magical powers."],
    ["bracers", 0, "armor", "Protective arm-wear that reduces damage taken."],
    ["greaves", 0, "armor", "Protective leg-wear that reduces damage taken."],
    ["cuirass", 0, "armor", "A breastplate that reduces damage taken."],
    ["pizza-variant italia", 0, "consumable", "a dish of Italian origin consisting of a usually round, flat base of leavened wheat-based dough topped with tomatoes, cheese, and often various other ingredients (such as various types of sausage, anchovies, mushrooms, onions, olives, vegetables, meat, ham, etc.), which is then baked at a high temperature, traditionally in a wood-fired oven. "],
    ["water", 0, "consumable", "A liquid that restores health and energy."],
    ["torch", 0, "tool", "A portable light source."],
    ["rope", 0, "tool", "A long, strong cord used for climbing and binding."],
    ["grappling hook", 0, "tool", "A hook attached to a rope used for climbing."],
    ["lockpick", 0, "tool", "A tool used for picking locks."],
    ["key", 0, "tool", "A small metal object used for unlocking doors."],
    ["map", 0, "tool", "A diagram that shows the layout of an area."],
    ["compass", 0, "tool", "A device that shows the cardinal directions."],
    ["flint and steel", 0, "tool", "A tool used for starting fires."],
    ["fishing rod", 0, "tool", "A long, flexible rod used for catching fish."],
    ["tent", 0, "tool", "A portable shelter used for camping."],
    ["bedroll", 0, "tool", "A portable bed used for camping."],
    ["backpack", 0, "container", "A bag used for carrying items."],
    ["satchel", 0, "container", "A small bag used for carrying items."],
    ["pouch", 0, "container", "A small bag used for carrying small items."],
    ["quiver", 0, "container", "A container used for holding arrows or bolts."],
    ["scroll", 0, "tool", "A piece of parchment with a spell written on it."],
    ["book", 0, "tool", "A bound collection of pages with information written on them."],
    ["ink and quill", 0, "tool", "A tool used for writing."],
    ["herbs", 0, "consumable", "A plant used for its medicinal properties."],
    ["samosa", 0, "consumable", "A yummy food used for its Ambrosial properties."],
    ["gemstone", 0, "currency", "A valuable stone used for trading."],
    ["Pizza", 0, "consumable", "A savory dish of Italian origin, consisting of a usually round, flattened base of leavened wheat-based dough topped with tomatoes, cheese, and various other ingredients."],
    ["Sushi", 0, "consumable", "A Japanese dish of prepared vinegared rice, usually with some sugar and salt, accompanying a variety of ingredients, such as seafood, vegetables, and occasionally tropical fruits."],
    ["Tacos", 0,  "consumable", "A traditional Mexican dish consisting of a corn or wheat tortilla folded or rolled around a filling."],
    ["Burgers", 0,  "consumable", "A sandwich consisting of one or more cooked patties of ground meat, usually beef, placed inside a sliced bread roll or bun."],
    ["Pasta", 0,  "consumable", "A type of Italian noodle dish typically made from an unleavened dough of wheat flour mixed with water or eggs and formed into sheets or various shapes, then cooked by boiling or baking."],
    ["Ramen", 0,  "consumable", "A Japanese dish with Chinese origins, consisting of Chinese wheat noodles served in a meat or fish-based broth, often flavored with soy sauce or miso, and uses toppings such as sliced pork, dried seaweed, and green onions."],
    ["Curry", 0,  "consumable", "A variety of dishes originating in the Indian subcontinent that use a complex combination of spices or herbs, usually including ground turmeric, cumin, coriander, ginger, and fresh or dried chilies."],
    ["Steak", 0,  "consumable", "A cut of meat, usually beef, sliced perpendicular to the muscle fibers, potentially including a bone."],
    ["Fried Rice", 0,  "consumable", "A dish of cooked rice that has been stir-fried in a wok or a frying pan and is usually mixed with other ingredients such as eggs, vegetables, seafood, or meat."],
    ["Chow Mein", 0,  "consumable", "A Chinese stir-fried noodle dish which is popular in many countries."],
    ["Biryani", 0,  "consumable", "A mixed rice dish with its origins in the Indian subcontinent. It is made with Indian spices, rice, and meat, and sometimes, in addition, eggs and/or vegetables such as potatoes."],
    ["Lasagna", 0,  "consumable", "A wide, flat pasta noodle, usually baked in layers in the oven with a filling of either meat, cheese, or vegetables."],
    ["Fajitas", 0,  "consumable", "A Tex-Mex dish consisting of grilled meat usually served as a taco on a flour or corn tortilla."],
    ["Goulash", 0, "consumable", "A stew of meat and vegetables, seasoned with paprika and other spices."],
    ["Stroganoff", 0,  "consumable", "A Russian dish of sautéed pieces of beef served in a sauce with smetana."],
    ["Paella", 0,  "consumable", "A Valencian rice dish that has ancient roots but its modern form originated in the mid-19th century in the area around the Albufera lagoon on the east coast of Spain adjacent to the city of Valencia."],
    ["Ratatouille", 0,  "consumable", "A French Provençal stewed vegetable dish, originating in Nice, and sometimes referred to as ratatouille niçoise."],
    ["Chili con Carne", 0,  "consumable", "A spicy stew containing chili peppers, meat, and often tomatoes and beans."],
    ["Jambalaya", 0,  "consumable", "A Louisiana-origin dish of Spanish and French influence, consisting mainly of meat and vegetables mixed with rice."],
    ["Gumbo", 0,  "consumable", '''A stew that originated in southern Louisiana during the 18th century. It consists primarily of a strongly-flavored stock, meat or shellfish, a thickener, and the Cajun/Creole "holy trinity" ― celery, bell peppers, and onions.'''],
    ["Pierogi", 0,  "consumable", "A type of filled dumpling, originating from Central and Eastern Europe(mainly poland)."],
    ["Borscht", 0,  "consumable", '''A sour soup common in Eastern Europe and Northern Asia. In English, the word "borscht" is most often associated with the soup's variant of Ukrainian origin, made with beetroots as one of the main ingredients.'''],
    ["Schnitzel", 0,  "consumable", "A thin slice of meat fried in fat. The meat is usually thinned by pounding with a meat tenderizer. Most commonly, the meats are breaded before frying."],
    ["Kebab", 0, "consumable", "A dish of pieces of meat, fish, or vegetables roasted or grilled on"]
    ]